### PR TITLE
fix: don't continue to load if a specified file is not found

### PR DESCRIPTION
**Pull request by odilitime**
# Risks

Low

# Background

## What does this PR do?

If you specify a file to load, don't just load default and continue if you can't find it

## What kind of change is this?

UX clean up, should reduce confusion and reduce support issues

## Why are we doing this? Any context or related work?

# Documentation changes needed?

My changes do not require a change to the project documentation.

# Testing

I tested on stable-11-17 branch

### CODE REVIEW

**Comment by monilpat** [comment]
Please update the PR title other than that good to go!

**Comment by odilitime** [comment]
Where is the docs for PR titles? or what are the options?

**Comment by monilpat** [comment]
It is defined in the GH action see:
https://github.com/ai16z/eliza/actions/runs/11925717725/job/33238273772?pr=427

Please use the format: 'type: description' (e.g., 'feat: add new feature').

**Comment by odilitime** [comment]
ok so the title should be fine now

**Comment by monilpat** [comment]
Looks like the limitations are: feat|fix|docs|style|refactor|test|chore:any description see

 ```
 if [[ ! "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test|chore):\ .+ ]]; then
                    echo "PR title does not match the required pattern."
                    exit 1
                  fi
```

**Comment by monilpat** [comment]
LGTM! 🥇

**Pull request merged**
