### PR TITLE
Feat : github image cicd

### PR DESCRIPTION
**Pull request by v1xingyue**
when relase published make github docker image.

### CODE REVIEW

**Comment by monilpat** [comment]
Looks good to me do you mind adding a test thanks!

**Comment by v1xingyue** [comment]
I'm not sure what does test mean. This only do build and publish image when released. I think it should be tested and prepared for publish

**Comment by monilpat** [comment]
> I'm not sure what does test mean. This only do build and publish image when released. I think it should be tested and prepared for publish

I mean just adding a screenshot of successful run of the .yaml file.

**Comment by v1xingyue** [comment]
Ok that's fine I'll add that later

**Comment by v1xingyue** [comment]
This is one exmple running github cicd.
https://github.com/v1xingyue/eliza/actions/runs/12220378514/job/34088113118
I think this is enough for test.

But there is something wrong with `pnpm run build` in docker image.

**Comment by v1xingyue** [comment]
Done. Seems package.json provide 
pnpm build-docker 
command . 
I change it in Dockerfile .

**Review by odilitime — APPROVED** [review]

**Pull request merged**
