### PR TITLE
feat: add Aptos plugin

### PR DESCRIPTION
**Pull request by 0xaptosj**
# Relates to:

# Risks

# Background

## What does this PR do?

Introducing new plugin for agent to manage an Aptos wallet.

## What kind of change is this?

Now agent can manage an Aptos wallet and send APT token to others.

# Documentation changes needed?

# Testing

## Where should a reviewer start?

Go to the aptos-plugin directory. To keep things simple, I only support transferring APT at the moment. Will add more functionalities later.

## Detailed testing steps

Enable the aptos-plugin in the test agent, set the aptos wallet private key and network in .env.

For unit test, run `pnpm test` in plugin-aptos directory.

For end to end test, [replace default character at this line](https://github.com/ai16z/eliza/blob/6735003d4119d7e57f1355600a95cf432f53e42c/agent/src/index.ts#L463) with this custom character that enables aptos.
```
   const character = defaultCharacter;
    let customAptosPlugin = aptosPlugin;
    let customTransferAptToken = TransferAptosToken;
    customTransferAptToken.validate = async (content, runtime, callback) => {
        return true;
    };
    customAptosPlugin.actions = [customTransferAptToken];
    character.plugins = [customAptosPlugin];
    character.modelProvider = ModelProviderName.OPENAI;
    let characters = [character];
```

### CODE REVIEW

**Review by dermanyang — APPROVED** [review]

**Comment by 0xaptosj** [comment]
@shakkernerd gmgn ser I've added the unit test, feel free to take another look

**Comment by shakkernerd** [comment]
@0xaptosj GM - kudos for writing the tests. 
I am looking into this now.

**Review by shakkernerd — APPROVED** [review]
LFG Aptos!

**Comment by obsrvgmi** [comment]
lfg

**Pull request merged**
