### PR TITLE
fix: ollama local and llama local

### PR DESCRIPTION
**Pull request by yodamaster726**
# Ollama local broken and local llama issues
[Relates partially to issue #443 ](https://github.com/ai16z/eliza/issues/443)

# Risks

Low risk - affects only the Llama and Ollama - llama.ts

# Background
Eliza is supposed to be able to work with Ollama local and it was broken in several ways.  Wrong embeddings were being loaded.  Local llama was being downloaded even when the Ollama local was configured.

Model can be selected in the character by setting the ModelProviderName to LLAMALOCAL or OLLAMA
ex:  modelProvider: ModelProviderName.LLAMALOCAL

default ModelProvider can be set on the .env file by setting the OLLAMA_MODEL=  env variable

## What does this PR do?
- Fixes loading the correct embeddings file to be used depending on which llama model provider is selected
- Improved logging in embedddings, generation.
- Fixed bug in logger - was looking for lowercase environment variable instead  of VERBOSE=true 
- Improved the download progress indicator for the local llama model and other files.  
- Added a new method to logger for download progress % indicator
- I- Model provider validation in AgentRuntime and additional error logging
- Improved download and error logging in the Image provider
- Improved model provider in llama.ts

## What kind of change is this?
Bug fixes and improvements

# Documentation changes needed?
No, but might want to document the VERBOSE=true for more detailed logging for debugging purposes

# Testing
Tested for each of the providers LLAMALOCAL or OLLAMA

## Detailed testing steps
- update the model provider part for defaultCharacter.ts to one of the above,
- pnpm build
- pnpm start

For ollama local, you will need to install Ollama software and install the models that you will be using.
- mxbai-embed-large:latest  for the embeddings
- hermes3:latest  for the LLM

### CODE REVIEW

**Comment by ponderingdemocritus** [comment]
This is good and was working locally however few issues:

- LLAMA is still downloaded if external provider is used. Can you fix this.

**Comment by yodamaster726** [comment]
> This is good and was working locally however few issues:
> 
> * LLAMA is still downloaded if external provider is used. Can you fix this.
@ponderingdemocritus 

Which external provider ?  OpenAI ?  Where did you define it?  In the .env file or character?

I tested the different variations with OLLAMA ?

**Comment by ponderingdemocritus** [comment]
I tested with anthropic and it still inits OLLAMA

env is within character file

**Comment by yodamaster726** [comment]
> I tested with anthropic and it still inits OLLAMA
> 
> env is within character file

I updated defaultCharacter.ts with ANTHROPIC and it didn't try to download the llamalocal model.  It attempts to call the antropic api.  Do you have anything else in your .env related to llama definited ?  Are you on the latest code ?  

image

**Comment by ponderingdemocritus** [comment]
in the logs it tells me it has initalised

**Pull request merged**
