### PR TITLE
fix: Revert "docs: add WSL installation guide"

### PR DESCRIPTION
**Pull request by monilpat**
Reverts ai16z/eliza#946

### CODE REVIEW

**Comment by odilitime** [comment]
Why are we reverting this?

**Comment by monilpat** [comment]
The creator of the mentioned PR wanted to make some changes before merging as per: https://github.com/ai16z/eliza/pull/946 and am I currently AFK so reverting and having them resubmit with changes they want

**Review by jkbrooks — APPROVED** [review]

**Comment by jkbrooks** [comment]
Will revert for now @monilpat @odilitime , hopefully we get the fix in from @ileana-pr  ASAP

**Comment by ileana-pr** [comment]
@jkbrooks @monilpat @odilitime changes complete. added code to make page visible in Guides section and updated step 3 to use node 23. link to new pr here: https://github.com/ai16z/eliza/pull/983

**Pull request merged**
