### PR TITLE
feat: (voice) enhance character card voice configuration support

### PR DESCRIPTION
**Pull request by augchan42**
feat(voice): enhance character card voice configuration support
- Add comprehensive ElevenLabs configuration in character cards
- Make ElevenLabs settings optional with sensible defaults
- Implement configuration priority (character card > env vars > defaults)
- Update schema validation to support optional fields
- Add debug logging for voice selection process
- Maintain backward compatibility with existing setups

Example character card config:
```json
{
    "settings": {
        "voice": {
            "model": "en_GB-alan-medium",
            "elevenlabs": {
                "voiceId": "your-voice-id",
                "model": "eleven_monolingual_v1",
                "stability": "0.5"
            }
        }
    }
}
```

Closes https://github.com/ai16z/eliza/issues/694

### CODE REVIEW

**Comment by augchan42** [comment]
BTW this PR also fixes the web-agent/vite build issues

**Comment by shakkernerd** [comment]
> BTW this PR also fixes the web-agent/vite build issues

This is already fixed on recent main.

**Comment by shakkernerd** [comment]
Can you start by resolving the conflicts and why are there so many changed files? It says 141 files right now.

**Comment by augchan42** [comment]
The changed files are autogenearated docs from the build process.  I'll
take a look

**Comment by augchan42** [comment]
From 141 files to 8, I re-ran the build and it works after removing the web-agent folder (had to fix target in package.json)

**Pull request merged**
