### PR TITLE
fix: ensure unique instances for each Service subclass using Map

### PR DESCRIPTION
**Pull request by tcm390**
Previously, the Service base class used a single static instance, which caused
all subclasses to share the same instance. This update replaces the static
instance with a Map to manage unique instances for each subclass

### CODE REVIEW

**Comment by lalalune** [comment]
Many of the services load up models and such and we probably only want one instance, ever, enforcing the singleton pattern, if we add a map won't we have several instances of each class? That's why I made it this service pattern.

**Comment by tcm390** [comment]
> Many of the services load up models and such and we probably only want one instance, ever, enforcing the singleton pattern, if we add a map won't we have several instances of each class? That's why I made it this service pattern.

I see, but in the context of the Discord bot, we require two services: `ISpeechService` and `ITranscriptionService`. (Also, there are `IVideoService` and `IBrowserService`, but I'm not sure if these are necessary for the bot.) Would you like me to implement the Singleton pattern specifically for `ISpeechService` and `ITranscriptionService`, or would you prefer a different approach? Let me know how you'd like to proceed!

**Comment by lalalune** [comment]
I want one class of each service shared across all running agents, imagine we are running 10 agents, we want them to share the transcription service

**Comment by monilpat** [comment]
I agree with @lalalune we should close this PR as the singleton pattern would work best in this usecase.

**Comment by tcm390** [comment]
> I agree with @lalalune we should close this PR as the singleton pattern would work best in this usecase.

@monilpat thanks for the review but from my understanding, the current implementation ensures that each service type has its own singleton instance. This means only one instance of each subclass is created and reused. Could you clarify if the intent is different?

**Comment by monilpat** [comment]
> > I agree with @lalalune we should close this PR as the singleton pattern would work best in this usecase.
> 
> @monilpat thanks for the review but from my understanding, the current implementation ensures that each service type has its own singleton instance. This means only one instance of each subclass is created and reused. Could you clarify if the intent is different?

Yeah of course anytime! Here was my thought process if it helps: Should unrelated services (e.g., transcription and speech) share a single instance, or should each service type have its own singleton?
Are there current or future use cases where having service-specific singletons is necessary?
Recommendation:

If one global instance for all services is the clear requirement, stick with the static singleton approach.
If service-specific singleton instances are required now or likely in the future, proceed with the Map implementation to ensure flexibility and scalability.

**Comment by monilpat** [comment]
> > I agree with @lalalune we should close this PR as the singleton pattern would work best in this usecase.
> 
> @monilpat thanks for the review but from my understanding, the current implementation ensures that each service type has its own singleton instance. This means only one instance of each subclass is created and reused. Could you clarify if the intent is different?

Yeah of course anytime! The intent is not different. I just share @lalalune 's concern around multiple instances of service rather than a 1-> many from service -> agents.

**Pull request closed without merging**
