### PR TITLE
fix: refactor contributor page

### PR DESCRIPTION
**Pull request by tcm390**
# Relates to:

# Risks

# Background

## What kind of change is this?

# Documentation changes needed?

# Testing

### CODE REVIEW

**Comment by madjin** [comment]
nice looks like it's auto-updating the github contributor page now 

image

**Comment by madjin** [comment]
dark mode fixed and looks good
image
image

**Comment by madjin** [comment]
okay it looks good but wondering if we can do more than 2 columns
image

and if we can fetch the data from https://ai16z.github.io/data/contributors.json

**Comment by lalalune** [comment]
Good to go?

**Review by madjin — APPROVED** [review]
overall everything looks good, we just need to add an .env variable / modify this access token variable in repo settings as specified in the docusaurus.config.js

**Comment by madjin** [comment]
what if we had a workflow to update docs when pushing to docs branch?

```yml
name: Deploy Docs

on:
  push:
    branches:
      - docs
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9.4.0

      - uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Add the environment variable mapping here
      - name: Build website
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          ```

**Pull request merged**
