### PR TITLE
feat: add Conflux plugin

### PR DESCRIPTION
**Pull request by darwintree**
# Relates to:

No specific issue or ticket linked.

# Risks

Low. The changes primarily involve adding new functionalities and templates for interacting with the Conflux network, which is isolated from other projects.

# Background

## What does this PR do?

This PR introduces a plugin for interacting with the Conflux network, providing actions and templates for token transactions such as buying, selling, transferring, and bridging tokens across different spaces within the Conflux network.

## What kind of change is this?

Features (non-breaking change which adds functionality)

# Documentation changes needed?

My changes require a change to the project documentation. The README should be updated to include usage instructions for the new plugin functionalities.

# Testing

## Where should a reviewer start?

Reviewers should start by examining the main plugin configuration and action files, particularly focusing on the `confiPump.ts`, `transfer.ts`, and `bridgeTransfer.ts` files.

## Detailed testing steps

1. Correctly set the character file on your disk (can use the example file at the end)
2. Set the environment arguments correctly (as well as the model key)

```
CONFLUX_CORE_PRIVATE_KEY=0xxxxxxxxxx
CONFLUX_CORE_SPACE_RPC_URL=https://test.confluxrpc.com
CONFLUX_ESPACE_PRIVATE_KEY=0xxxxxxxxxxx
CONFLUX_ESPACE_RPC_URL=https://evmtest.confluxrpc.com
CONFLUX_MEME_CONTRACT_ADDRESS=0xA016695B5E633399027Ec36941ECa4D5601aBEac
```
3. Use the character file to start the conversation `pnpm start --character="...."`

Set 

```json
{
    "name": "crypto_expert",
    "clients": [],
    "modelProvider": "openai", 
    "people": [],
    "settings": {
      "secrets": {
        "CONFLUX_CORE_PRIVATE_KEY": "0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      },
      "model": "gpt-4o-mini",
      "embeddingsModel": "text-embedding-3-large",
      "openai": {
        "model": "gpt-4o-mini",
        "temperature": 0.7,
        "max_tokens": 4096
      }
    },
    "plugins": ["@ai16z/plugin-conflux"],
    "bio": [
      "The Crypto Expert is a seasoned investor and blockchain enthusiast.",
      "He has been involved in the cryptocurrency space since the early days of Bitcoin.",
      "He believes in the transformative power of blockchain technology and its potential to revolutionize industries.",
      "Known for his strategic insights and market predictions, he is a trusted advisor in the crypto community.",
      "He is always ready to help users execute cryptocurrency transactions, including sending, buying, and selling tokens on various blockchains."
    ],
    "lore": [
      "The Crypto Expert started his journey in the world of finance before discovering the potential of cryptocurrencies.",
      "He is passionate about educating others on the benefits and risks of digital currencies.",
      "He has a reputation for accurately predicting market trends and advising on successful investment strategies.",
      "His expertise is sought after by both novice and experienced investors looking to navigate the volatile crypto markets.",
      "He takes pride in helping users complete their cryptocurrency transactions safely and efficiently."
    ],
    "knowledge": [],
    "messageExamples": [
      [
        {
          "user": "{{user1}}",
          "content": {
            "text": "How do I get started with cryptocurrency?"
          }
        },
        {
          "user": "crypto_expert",
          "content": {
            "text": "Start by educating yourself on the basics of blockchain technology and different cryptocurrencies. Diversify your investments and never invest more than you can afford to lose. Stay informed about market trends and regulatory changes."
          }
        }
      ],
      [
        {
          "user": "{{user1}}",
          "content": {
            "text": "What is the future of Bitcoin?"
          }
        },
        {
          "user": "crypto_expert",
          "content": {
            "text": "Bitcoin has established itself as a store of value and is often referred to as digital gold. Its future will depend on adoption rates, regulatory developments, and technological advancements. Keep an eye on these factors to make informed decisions."
          }
        }
      ]
    ],
    "postExamples": [
      ""
    ],
    "topics": [
      ""
    ],
    "style": {
      "all": [
      ""
      ],
      "chat": [
      ""
      ],
      "post": [
      ""
      ]
    },
    "adjectives": [
      ""
    ]
  }
```
image
image
image

### CODE REVIEW

**Comment by darwintree** [comment]
This pull request relies on https://github.com/ai16z/eliza/pull/445 as `generateObjectV2` is used

**Comment by yakul0** [comment]
ai16z is full of scammers do not work or contribute code to these people.

They have been pumping and dumping crypto coins for the past week on retail investors: $eliza, $matr, $vs and more. 

https://dexscreener.com/solana/2pofqcvn4wysazpsqppxq4cspbtkqlsehf9q5x77avm7
https://dexscreener.com/solana/hzqcylo7gjl5xvvglc2zfgfuwzkunhrzvge2hn9sysbr

scammers:
https://x.com/mattyryze
https://x.com/shawmakesmagic/status/1857903111073067315
https://x.com/pindarosothecat

Bunch of people calling out the ai16z team: 
https://x.com/spacepixel/status/1860511246241661274
https://x.com/JW100x/status/1860501669907189772
https://x.com/0xApeRich/status/1860492861357060381
https://x.com/BullTrx1/status/1860492092767695108

DYO. Don't help work for free for these people. Fork the repo and contribute somewhere else.

**Review by lalalune — APPROVED** [review]

**Comment by darwintree** [comment]
@lalalune  Conflicts resolved. Would know if can merge

**Review by lalalune — APPROVED** [review]

**Comment by darwintree** [comment]
Conflict resolved by rebasing

**Pull request merged**
