### PR TITLE
LinkedIn Client

### PR DESCRIPTION
**Pull request by bkellgren**
# Risks

Medium - Rate Limiting  - Dependent on adhering to rate limits which we have tried to help developers with via defaults
Medium - I've done minimal testing so far, please halp!

# Background

## What does this PR do?

New client for supporting Eliza integrating with LinkedIn

# Documentation changes needed?

I include a README but maybe some mention in the main Eliza README would be nice

# Testing

I minimally tested but would love more help testing further.

## Discord username

yourfriendbrett

### CODE REVIEW

**Comment by MuhovTheDev** [comment]
@bkellgren can I contact you and can we talk somehow? What is your twitter account?

**Comment by MuhovTheDev** [comment]
@bkellgren we want to help you in regarding Brett, and his token. Please contact me somehow.

**Comment by amesemyta1** [comment]
Hi. How can I install this plugin? When I run the installation I get an error

`deval@superagi:~/eliza$ pnpm add @ai16z/client-linkedin
 ERR_PNPM_ADDING_TO_ROOT  Running this command will add the dependency to the workspace root, which might not be what you want - if you really meant it, make it explicit by running this command again with the -w flag (or --workspace-root). If you don't want to see this warning anymore, you may set the ignore-workspace-root-check setting to true.
deval@superagi:~/eliza$ cd client
deval@superagi:~/eliza/client$ pnpm add @ai16z/client-linkedin
..                                       |  WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@ai16z%2Fclient-linkedin: Not Found - 404

This error happened while installing a direct dependency of /home/deval/eliza/client

@ai16z/client-linkedin is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
..                                       | Progress: resolved 1, reused 0, downloaded 0, added 0
deval@superagi:~/eliza/client$ pnpm install
Scope: all 35 workspace projects
..                                       | -148 ---------------
..                                       | Progress: resolved 0, reused 148, downloaded 0, added 0, done
../packages/plugin-node postinstall$ node scripts/postinstall.js
│ Skipping playwright installation on unsupported platform: linux
└─ Done in 38ms
Done in 5s
deval@superagi:~/eliza/client$ cd ../
deval@superagi:~/eliza$ cd agent
deval@superagi:~/eliza/agent$ pnpm add @ai16z/client-linkedin
..                                       |  WARN  `node_modules` is present. Lockfile only installation will make it out-of-date
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@ai16z%2Fclient-linkedin: Not Found - 404

This error happened while installing a direct dependency of /home/deval/eliza/agent

@ai16z/client-linkedin is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
..                                       | Progress: resolved 1, reused 0, downloaded 0, added 0
deval@superagi:~/eliza/agent$`

**Comment by houssemmechri** [comment]
same issue
if you find a solution please share it with me

**Comment by amesemyta1** [comment]
From what I did
in the file eliza\agent\src\index.ts I added import { LinkedInClientInterface } from '@ai16z/client-linkedin';
if (clientTypes.includes("linkedin")) {
const linkedInClients= await LinkedInClientInterface.start(runtime);
clients.push(linkedInClients);
}
in the file .env I added
LINKEDIN_USERNAME=
LINKEDIN_PASSWORD=
LINKEDIN_DRY_RUN=false
POST_INTERVAL_MIN=10
POST_INTERVAL_MAX=30
and in characters I added "clients": ["linkedin"]

I did pnpm build
and now I get these errors
image

image

**Pull request merged**
