### PR TITLE
chore: remove TWITTER_COOKIES env var

### PR DESCRIPTION
**Pull request by ChristopherTrimboli**
# Relates to:

No issue ticket, just a improvement, ease of setup change I noticed.

# Risks

LOW - Twitter may not login? But tested with clearing cache and cached, working great.

# Background

## What does this PR do?

This PR removes the .env variable TWITTER_COOKIES and simply uses twitterScraper to manage cookies on login better from cache.

It also removes the docs / readme step where user has to provide the JSON array of TWITTER_COOKIES.

Side win: the looping try-catch while loop is cleaner to read, deleted many lines of code in simpler implementation for twitter auth.

## What kind of change is this?

Improvements

## Why are we doing this? Any context or related work?

TWITTER_COOKIES env var is an added complexity not required, users have to go searching in dev-tools console `document.cookie` and rearrange their JSON and add to ENV. But, twitter-scraper client has support for login + fetch current cookies on it's own. It is a redundant ENV setup that can be removed to simplify the twitter agent setup process for all users.

I recently implemented twitter-scapper-client in my own custom agent and never had todo this ENV setup, I saw it as a EZ win for Eliza community to port over.

# Documentation changes needed?

If a docs change is needed: I have updated the documentation accordingly.

I have removed the TWITTER_COOKIES docs sections, full deletion, no longer needed.

Please show how you tested the PR. This will really help if the PR needs to be retested, and probably help the PR get merged quicker. 

image

I also ran:

```javascript
return await this.runtime.cacheManager.delete(
    `twitter/${username}/cookies`
);
```

To delete the cookies from cache manually to verify my code was working.

# Testing

## Where should a reviewer start?

Remove TWITTER_COOKIES from .env and see if Twitter agent boots correctly and works from fresh cache and already cached.

## Detailed testing steps

None, automated tests are fine. 

# Deploy Notes

Remove TWITTER_COOKIES from any CI / CD and .env test runners.

## Discord username

cjft

### CODE REVIEW

**Review by monilpat — APPROVED** [review]
LGTM - thanks for consolidating this on the client side :)

**Comment by touhonoob** [comment]
Getting `DenyLoginSubtask` with the new login method
 
```
 ["⛔ Failed to login to Twitter. Retrying... (0 attempts left)"] 

 ["⛔ Max retries reached. Exiting login process."] 
```

**Comment by adamcanray** [comment]
> Getting `DenyLoginSubtask` with the new login method
> 
> ```
>  ["⛔ Failed to login to Twitter. Retrying... (0 attempts left)"] 
> 
>  ["⛔ Max retries reached. Exiting login process."] 
> ```

+1

**Comment by daniel-farina** [comment]
I think we should remove this as loging with cookies is the only method that works currently. On a fresh installation login with username/pw fails. Once I revert this PR and add cookies everything works. 

cc: @monilpat @lalalune

**Comment by YOLOcult** [comment]
I can't agree to any more, the 1.6 version doesn't prompt me to log in no matter how I try, and starting from version 1.7 every login results in an error message, which is very frustrating. This isn't cool.

**Comment by YOLOcult** [comment]
> I can't agree to any more, the 1.6 version doesn't prompt me to log in no matter how I try, and starting from version 1.7 every login results in an error message, which is very frustrating. This isn't cool.

I viewed the reviewed changes and reverted the code, and now the Twitter login is working perfectly.
Screenshot_2024-12-14_at_11

**Pull request merged**
