### PR TITLE
fix: (core) Add circuit breaker pattern for database operations

### LINKED ISSUE #712: feat: Add circuit breaker pattern for database operations
Implements a circuit breaker pattern to handle database failures gracefully and prevent cascading failures. This change:

- Adds CircuitBreaker class with CLOSED, OPEN, and HALF-OPEN states
- Introduces BaseCircuitBreakerAdapter for database adapters
- Configurable failure thresholds and recovery timeouts
- Automatic recovery attempts in HALF-OPEN state
- Detailed logging of circuit breaker state changes

The circuit breaker will:
- Open after 5 consecutive failures (configurable)
- Reset after 60 seconds in OPEN state
- Require 3 successful operations in HALF-OPEN state to close

This helps prevent overwhelming failed database connections and provides 
graceful degradation during outages.

### PR DESCRIPTION
**Pull request by augchan42**
Implements circuit breaker pattern to handle database failures gracefully and prevent cascading failures. Fixes #712.

Changes:
- Adds CircuitBreaker class with CLOSED, OPEN, and HALF-OPEN states
- Introduces BaseCircuitBreakerAdapter for database adapters
- Configurable failure thresholds and recovery timeouts
- Automatic recovery attempts in HALF-OPEN state
- Detailed logging of circuit breaker state changes

Circuit breaker configuration:
- Opens after 5 consecutive failures (configurable)
- Resets after 60 seconds in OPEN state
- Requires 3 successful operations in HALF-OPEN state to close

This helps prevent overwhelming failed database connections and provides graceful degradation during outages.

## Discord username
hosermage

### CODE REVIEW

**Comment by shakkernerd** [comment]
Hi, this looks good to me but changes the overall use of DatabaseAdapter. Hence, I think might cause breaking changes.
Is there anyway you could implement this into the DatabaseAdapter class itself?

**Comment by augchan42** [comment]
Ok, I changed the code to the way I think you wanted... please take a look.

**Comment by shakkernerd** [comment]
Great, now its better.
I will test locally and then merge in if no issue.

**Comment by lalalune** [comment]
lgtm, will leave for @shakkernerd to merge
We're moving fast, so there are some small merge conflicts in package lock, whoever is maintaining can just fix and merge

**Comment by shakkernerd** [comment]
Hi @augchan42 could you kindly fix the conflicts.
Will merge in once its done.
Thanks!

**Pull request closed without merging**
