### PR TITLE
Model provider abstraction

### PR DESCRIPTION
**Pull request by lalalune**
Adds model provider abstraction, WIP not ready

### CODE REVIEW

**Comment by lalalune** [comment]
@sirkitree please take a look. I think we need to consider secrets management, but I tested with OpenAI. I think you'll agree it is much better :)

**Review by sirkitree — COMMENTED** [review]
Whoa. Dat's a bigun... I'm not knowledgeable enough with this codebase yet to provide valid feedback in terms of saying this is good or not.

I'd prefer if you had an issue for this PR, referenced issues that are relevant to the change, and explained the changes and steps to test in your PR. Large PR out of the blue is how this feels currently... 

I definitely would like some testing steps.

but let's see here...

Overall you're trying to provide some model abstraction.

## Provide More Models
- anthropic
- google
- groq
- The abstraction in src/core/models.ts is interesting, looks good at the outset but not sure how to test.

## Pumpfun
- added some constants that are passed along for context

## Order book
- uncommented a lot of code here, which introduces some basic order book functionality

## Embeddings
- I'm not clear on what all this is doing, but I gather  it's somehow used in the core memory

## Error Handling Improvements
- Adds proper error handling for cases where no appropriate response pattern is found
- Implements a fallback mechanism to provide default responses when specific patterns aren't matched

## Response Formatting
- Enhances the formatting of bot responses to ensure consistency
- Modifies the way responses are structured and returned to the user

## Code Organization
- Refactors the response selection logic to be more maintainable
- Streamlines the pattern matching process for better efficiency

**Comment by sirkitree** [comment]
Is this for resolving #72 ?

**Comment by lalalune** [comment]
No, this is for dealing with the horribly API key management. It makes it so you just set a model provider in your character file and it uses that one. Replaces a lot of very fragile code.

**Pull request merged**
